# Generated by Django 3.2.5 on 2021-07-19 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210718_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_people',
            field=models.ManyToManyField(blank=True, related_name='tagged_people', to=settings.AUTH_USER_MODEL),
        ),
    ]
