# Generated by Django 3.2.5 on 2021-07-19 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20210719_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_people',
            field=models.ManyToManyField(blank=True, related_name='like_people', to=settings.AUTH_USER_MODEL),
        ),
    ]
