# Generated by Django 3.2.5 on 2021-07-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
    ]
