# Generated by Django 3.2.5 on 2021-07-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210729_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
