# Generated by Django 3.2.5 on 2021-07-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210729_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
