# Generated by Django 3.2.5 on 2021-08-17 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_postactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postactivity',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postactivity',
            name='post',
            field=models.CharField(max_length=100),
        ),
    ]
