# Generated by Django 3.2.5 on 2021-08-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210817_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postactivity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
