# Generated by Django 3.2.5 on 2021-08-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_postactivity_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postactivity',
            name='post',
            field=models.CharField(max_length=100),
        ),
    ]
