# Generated by Django 3.2.5 on 2021-08-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_postactivity_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPost',
        ),
    ]
