# Generated by Django 3.2.4 on 2021-06-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialflyuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('R', 'Rather Not To Say')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
