# Generated by Django 3.2.5 on 2021-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_genuineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuineuser',
            name='reject',
            field=models.BooleanField(default=False, help_text='if reject is true then use can mot send addition requests'),
        ),
    ]
