# Generated by Django 3.1.4 on 2021-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialflyuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialflyuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile-pic.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
