# Generated by Django 3.2.4 on 2021-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialflyuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialflyuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=''),
        ),
    ]
