# Generated by Django 3.2.4 on 2021-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_socialflyuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialflyuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='photo.jpeg', null=True, upload_to=''),
        ),
    ]
