# Generated by Django 3.2.5 on 2021-09-14 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_genuineuser_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuineuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 14, 5, 40, 25, 417013, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genuineuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genuineuser',
            name='reject',
            field=models.BooleanField(default=False, help_text="if reject is true then user can'not send addition requests"),
        ),
    ]
