# Generated by Django 3.2.4 on 2021-07-01 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_socialflyuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialflyuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialflyuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialflyuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('R', 'Rather Not To Say')], default='R', max_length=1),
        ),
    ]
