# Generated by Django 3.2.4 on 2021-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210701_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialflyuser',
            name='profile_photo',
            field=models.ImageField(default='photo.jpeg', upload_to=''),
        ),
    ]
