# Generated by Django 3.2.4 on 2021-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_socialflyuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialflyuser',
            name='profile_photo',
            field=models.ImageField(default='photo.jpeg', upload_to='profile_photo'),
        ),
    ]
