# Generated by Django 3.2.5 on 2021-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_socialflyuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialflyuser',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
