# Generated by Django 3.2.5 on 2021-07-15 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_historicalsocialflyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsocialflyuser',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
