# Generated by Django 3.2.5 on 2021-07-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_historicalsocialflyuser_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsocialflyuser',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
