# Generated by Django 3.2.5 on 2021-07-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_historicalsocialflyuser_history_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSocialflyUser',
        ),
    ]
