# Generated by Django 3.2.5 on 2021-08-17 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
