# Generated by Django 3.2.5 on 2021-08-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_useractivity_changed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSocialflyUser',
        ),
    ]
