# Generated by Django 3.2.5 on 2021-08-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='str_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
